name: Hata bildirimi
description: Sorun mu var?
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: Ne oldu?
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: İşletim sistemi
    validations:
      required: true
